language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      addons:
        sonarcloud:
          organization: "xylene1980-github"
          token:
            secure: "$SONAR_TOKEN"

        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
install:
  - pwsh Install-Dependencies.ps1
script:
  - sonar-scanner -Dsonar.organization=xylene1980-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=74b5a406d4faa6475d458824
332bb7ec1d9db028
  - pwsh Invoke-Build.ps1
