language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      addons:
        sonarcloud:
          organization: "xylene1980-github"
          token:
            secure: "$SONAR_TOKEN"

        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
install:
  - pwsh Install-Dependencies.ps1
script:
  - sonar-scanner
  - pwsh Invoke-Build.ps1
