language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          packages:
            - powershell
script:
  - pwsh -f "${env:TRAVIS_BUILD_DIR}/setup-scripts/test.ps1"
