language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
# install:
#   - pwsh Install-BuildPrerequisite.ps1
script:
  - pwsh -f "setup-scripts/test.ps1"
