image: Visual Studio 2015
branches:
  only:
    - master
install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: .\setup-scripts\Set-GitConfiguration.ps1 -reply S.Jacob s@to.com
  - ps: .\Install-BuildPrerequisite.ps1

build_script:
  - ps: .\Invoke-Build.ps1 -AppVeyor
after_build:
  - ps: .\setup-scripts\Install-JDK-Tests.ps1

#test
